/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuestionTypeDTO = IDL.Variant({
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const QuestionDTO = IDL.Record({
  'option_a_en' : IDL.Text,
  'option_a_ta' : IDL.Text,
  'option_b_en' : IDL.Text,
  'option_b_ta' : IDL.Text,
  'option_c_en' : IDL.Text,
  'option_c_ta' : IDL.Text,
  'option_d_en' : IDL.Text,
  'option_d_ta' : IDL.Text,
  'question_type' : QuestionTypeDTO,
  'question_order' : IDL.Nat,
  'test_key' : IDL.Text,
  'question_text_en' : IDL.Text,
  'question_text_ta' : IDL.Text,
  'is_active' : IDL.Bool,
  'question_image_en' : IDL.Vec(IDL.Nat8),
  'question_image_ta' : IDL.Vec(IDL.Nat8),
  'correct_answer_en' : IDL.Text,
  'correct_answer_ta' : IDL.Text,
});
export const QuestionId = IDL.Nat;
export const RegistrationId = IDL.Nat;
export const QuizResponseId = IDL.Nat;
export const QuizResponse = IDL.Record({
  'id' : QuizResponseId,
  'question_text' : IDL.Text,
  'is_correct' : IDL.Bool,
  'correct_answer' : IDL.Text,
  'time_taken' : IDL.Nat,
  'score' : IDL.Nat,
  'question_index' : IDL.Nat,
  'student_answer' : IDL.Text,
  'registration_id' : RegistrationId,
  'total_questions' : IDL.Nat,
  'percentage' : IDL.Float64,
  'submitted_at' : IDL.Int,
});
export const Registration = IDL.Record({
  'id' : RegistrationId,
  'student_name' : IDL.Text,
  'registration_date' : IDL.Int,
  'test_key' : IDL.Text,
  'contact_number' : IDL.Text,
  'whatsapp_number' : IDL.Text,
  'exam_group' : IDL.Text,
  'school_name' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createQuestion' : IDL.Func([QuestionDTO], [QuestionId], []),
  'createRegistration' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [RegistrationId],
      [],
    ),
  'deleteRegistration' : IDL.Func([RegistrationId], [], []),
  'getAllQuizResponses' : IDL.Func([], [IDL.Vec(QuizResponse)], ['query']),
  'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestionsByTestKey' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Vec(QuestionDTO)],
      ['query'],
    ),
  'getResponsesByRegistrationId' : IDL.Func(
      [RegistrationId],
      [IDL.Vec(QuizResponse)],
      ['query'],
    ),
  'getTopQuizScores' : IDL.Func([IDL.Nat], [IDL.Vec(QuizResponse)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitQuizResponse' : IDL.Func(
      [
        RegistrationId,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
      ],
      [QuizResponseId],
      [],
    ),
  'toggleQuestionActive' : IDL.Func([QuestionId], [], []),
  'updateQuestion' : IDL.Func([QuestionId, QuestionDTO], [], []),
  'deleteQuestionByTestKeyAndOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuestionTypeDTO = IDL.Variant({
    'text' : IDL.Null,
    'image' : IDL.Null,
  });
  const QuestionDTO = IDL.Record({
    'option_a_en' : IDL.Text,
    'option_a_ta' : IDL.Text,
    'option_b_en' : IDL.Text,
    'option_b_ta' : IDL.Text,
    'option_c_en' : IDL.Text,
    'option_c_ta' : IDL.Text,
    'option_d_en' : IDL.Text,
    'option_d_ta' : IDL.Text,
    'question_type' : QuestionTypeDTO,
    'question_order' : IDL.Nat,
    'test_key' : IDL.Text,
    'question_text_en' : IDL.Text,
    'question_text_ta' : IDL.Text,
    'is_active' : IDL.Bool,
    'question_image_en' : IDL.Vec(IDL.Nat8),
    'question_image_ta' : IDL.Vec(IDL.Nat8),
    'correct_answer_en' : IDL.Text,
    'correct_answer_ta' : IDL.Text,
  });
  const QuestionId = IDL.Nat;
  const RegistrationId = IDL.Nat;
  const QuizResponseId = IDL.Nat;
  const QuizResponse = IDL.Record({
    'id' : QuizResponseId,
    'question_text' : IDL.Text,
    'is_correct' : IDL.Bool,
    'correct_answer' : IDL.Text,
    'time_taken' : IDL.Nat,
    'score' : IDL.Nat,
    'question_index' : IDL.Nat,
    'student_answer' : IDL.Text,
    'registration_id' : RegistrationId,
    'total_questions' : IDL.Nat,
    'percentage' : IDL.Float64,
    'submitted_at' : IDL.Int,
  });
  const Registration = IDL.Record({
    'id' : RegistrationId,
    'student_name' : IDL.Text,
    'registration_date' : IDL.Int,
    'test_key' : IDL.Text,
    'contact_number' : IDL.Text,
    'whatsapp_number' : IDL.Text,
    'exam_group' : IDL.Text,
    'school_name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createQuestion' : IDL.Func([QuestionDTO], [QuestionId], []),
    'createRegistration' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [RegistrationId],
        [],
      ),
    'deleteRegistration' : IDL.Func([RegistrationId], [], []),
    'getAllQuizResponses' : IDL.Func([], [IDL.Vec(QuizResponse)], ['query']),
    'getAllRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestionsByTestKey' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Vec(QuestionDTO)],
        ['query'],
      ),
    'getResponsesByRegistrationId' : IDL.Func(
        [RegistrationId],
        [IDL.Vec(QuizResponse)],
        ['query'],
      ),
    'getTopQuizScores' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuizResponse)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitQuizResponse' : IDL.Func(
        [
          RegistrationId,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
        ],
        [QuizResponseId],
        [],
      ),
    'toggleQuestionActive' : IDL.Func([QuestionId], [], []),
    'updateQuestion' : IDL.Func([QuestionId, QuestionDTO], [], []),
    'deleteQuestionByTestKeyAndOrder' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };