/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface QuestionDTO {
  'option_a_en' : string,
  'option_a_ta' : string,
  'option_b_en' : string,
  'option_b_ta' : string,
  'option_c_en' : string,
  'option_c_ta' : string,
  'option_d_en' : string,
  'option_d_ta' : string,
  'question_type' : QuestionType,
  'question_order' : bigint,
  'test_key' : string,
  'question_text_en' : string,
  'question_text_ta' : string,
  'is_active' : boolean,
  'question_image_en' : Uint8Array,
  'question_image_ta' : Uint8Array,
  'correct_answer_en' : string,
  'correct_answer_ta' : string,
}
export type QuestionId = bigint;
export type QuestionType = { 'text' : null } |
  { 'image' : null };
export interface QuizResponse {
  'id' : QuizResponseId,
  'question_text' : string,
  'is_correct' : boolean,
  'correct_answer' : string,
  'time_taken' : bigint,
  'score' : bigint,
  'question_index' : bigint,
  'student_answer' : string,
  'registration_id' : RegistrationId,
  'total_questions' : bigint,
  'percentage' : number,
  'submitted_at' : bigint,
}
export type QuizResponseId = bigint;
export interface Registration {
  'id' : RegistrationId,
  'student_name' : string,
  'registration_date' : bigint,
  'test_key' : string,
  'contact_number' : string,
  'whatsapp_number' : string,
  'exam_group' : string,
  'school_name' : string,
}
export type RegistrationId = bigint;
export interface StudentCredentials {
  'password' : string,
  'user_id' : string,
  'contact_number' : string,
  'is_active' : boolean,
  'registration_id' : RegistrationId,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addQuestion' : ActorMethod<[QuestionDTO], QuestionId>,
  'addRegistration' : ActorMethod<
    [string, string, string, string, string, string],
    RegistrationId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteQuestion' : ActorMethod<[QuestionId], undefined>,
  'deleteRegistration' : ActorMethod<[RegistrationId], undefined>,
  'filterQuizResponses' : ActorMethod<[RegistrationId], Array<QuizResponse>>,
  'generateStudentCredentials' : ActorMethod<
    [RegistrationId, string],
    { 'password' : string, 'user_id' : string }
  >,
  'getAllStudentCredentials' : ActorMethod<[], Array<StudentCredentials>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCredentialsByRegistrationId' : ActorMethod<
    [RegistrationId],
    [] | [StudentCredentials]
  >,
  'getFast2SmsApiKey' : ActorMethod<[], string>,
  'getQuestion' : ActorMethod<[QuestionId], [] | [QuestionDTO]>,
  'getQuizResponse' : ActorMethod<[QuizResponseId], [] | [QuizResponse]>,
  'getRegistration' : ActorMethod<[RegistrationId], [] | [Registration]>,
  'getSmsStats' : ActorMethod<
    [],
    { 'total_failed' : bigint, 'api_key_set' : boolean, 'total_sent' : bigint }
  >,
  'getTopQuizScores' : ActorMethod<[bigint], Array<QuizResponse>>,
  'httpTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listQuestions' : ActorMethod<[string, boolean], Array<QuestionDTO>>,
  'listQuizResponses' : ActorMethod<[], Array<QuizResponse>>,
  'listRegistrations' : ActorMethod<[], Array<Registration>>,
  'sendTestSms' : ActorMethod<[string, string], boolean>,
  'setFast2SmsApiKey' : ActorMethod<[string], undefined>,
  'submitQuizResponse' : ActorMethod<
    [
      RegistrationId,
      bigint,
      string,
      string,
      string,
      boolean,
      bigint,
      bigint,
      number,
      bigint,
    ],
    QuizResponseId
  >,
  'toggleQuestionActive' : ActorMethod<[QuestionId], undefined>,
  'updateQuestion' : ActorMethod<[QuestionId, QuestionDTO], undefined>,
  'validateStudentLogin' : ActorMethod<
    [string, string],
    { 'test_key' : string, 'registration_id' : RegistrationId }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];