/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionType = IDL.Variant({
  'text' : IDL.Null,
  'image' : IDL.Null,
});
export const QuestionDTO = IDL.Record({
  'option_a_en' : IDL.Text,
  'option_a_ta' : IDL.Text,
  'option_b_en' : IDL.Text,
  'option_b_ta' : IDL.Text,
  'option_c_en' : IDL.Text,
  'option_c_ta' : IDL.Text,
  'option_d_en' : IDL.Text,
  'option_d_ta' : IDL.Text,
  'question_type' : QuestionType,
  'question_order' : IDL.Nat,
  'test_key' : IDL.Text,
  'question_text_en' : IDL.Text,
  'question_text_ta' : IDL.Text,
  'is_active' : IDL.Bool,
  'question_image_en' : IDL.Vec(IDL.Nat8),
  'question_image_ta' : IDL.Vec(IDL.Nat8),
  'correct_answer_en' : IDL.Text,
  'correct_answer_ta' : IDL.Text,
});
export const QuestionId = IDL.Nat;
export const RegistrationInput = IDL.Record({
  'student_name' : IDL.Text,
  'mother_name' : IDL.Text,
  'test_key' : IDL.Text,
  'aadhaar' : IDL.Text,
  'parent_mobile' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'contact_number' : IDL.Text,
  'whatsapp_number' : IDL.Text,
  'exam_group' : IDL.Text,
  'date_of_birth' : IDL.Text,
  'choice1' : IDL.Text,
  'choice2' : IDL.Text,
  'choice3' : IDL.Text,
  'school_name' : IDL.Text,
  'father_name' : IDL.Text,
});
export const RegistrationId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuizResponseId = IDL.Nat;
export const QuizResponse = IDL.Record({
  'id' : QuizResponseId,
  'question_text' : IDL.Text,
  'is_correct' : IDL.Bool,
  'correct_answer' : IDL.Text,
  'time_taken' : IDL.Nat,
  'score' : IDL.Nat,
  'question_index' : IDL.Nat,
  'student_answer' : IDL.Text,
  'registration_id' : RegistrationId,
  'total_questions' : IDL.Nat,
  'percentage' : IDL.Float64,
  'submitted_at' : IDL.Int,
});
export const StudentCredentials = IDL.Record({
  'password' : IDL.Text,
  'user_id' : IDL.Text,
  'contact_number' : IDL.Text,
  'is_active' : IDL.Bool,
  'registration_id' : RegistrationId,
});
export const Registration = IDL.Record({
  'id' : RegistrationId,
  'student_name' : IDL.Text,
  'mother_name' : IDL.Text,
  'registration_date' : IDL.Int,
  'test_key' : IDL.Text,
  'aadhaar' : IDL.Text,
  'parent_mobile' : IDL.Text,
  'email' : IDL.Text,
  'district' : IDL.Text,
  'contact_number' : IDL.Text,
  'whatsapp_number' : IDL.Text,
  'exam_group' : IDL.Text,
  'date_of_birth' : IDL.Text,
  'choice1' : IDL.Text,
  'choice2' : IDL.Text,
  'choice3' : IDL.Text,
  'school_name' : IDL.Text,
  'father_name' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addQuestion' : IDL.Func([QuestionDTO], [QuestionId], []),
  'addRegistration' : IDL.Func([RegistrationInput], [RegistrationId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteQuestion' : IDL.Func([QuestionId], [], []),
  'deleteRegistration' : IDL.Func([RegistrationId], [], []),
  'filterQuizResponses' : IDL.Func(
      [RegistrationId],
      [IDL.Vec(QuizResponse)],
      ['query'],
    ),
  'generateStudentCredentials' : IDL.Func(
      [RegistrationId, IDL.Text],
      [IDL.Record({ 'password' : IDL.Text, 'user_id' : IDL.Text })],
      [],
    ),
  'getAllStudentCredentials' : IDL.Func(
      [],
      [IDL.Vec(StudentCredentials)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCredentialsByRegistrationId' : IDL.Func(
      [RegistrationId],
      [IDL.Opt(StudentCredentials)],
      ['query'],
    ),
  'getFast2SmsApiKey' : IDL.Func([], [IDL.Text], ['query']),
  'getQuestion' : IDL.Func([QuestionId], [IDL.Opt(QuestionDTO)], ['query']),
  'getQuizResponse' : IDL.Func(
      [QuizResponseId],
      [IDL.Opt(QuizResponse)],
      ['query'],
    ),
  'getRegistration' : IDL.Func(
      [RegistrationId],
      [IDL.Opt(Registration)],
      ['query'],
    ),
  'getSmsStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'total_failed' : IDL.Nat,
          'api_key_set' : IDL.Bool,
          'total_sent' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTopQuizScores' : IDL.Func([IDL.Nat], [IDL.Vec(QuizResponse)], ['query']),
  'httpTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listQuestions' : IDL.Func(
      [IDL.Text, IDL.Bool],
      [IDL.Vec(QuestionDTO)],
      ['query'],
    ),
  'listQuizResponses' : IDL.Func([], [IDL.Vec(QuizResponse)], ['query']),
  'listRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
  'sendSmsCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'sendTestSms' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool, IDL.Text], []),
  'setFast2SmsApiKey' : IDL.Func([IDL.Text], [], []),
  'submitQuizResponse' : IDL.Func(
      [
        RegistrationId,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
      ],
      [QuizResponseId],
      [],
    ),
  'toggleQuestionActive' : IDL.Func([QuestionId], [], []),
  'updateQuestion' : IDL.Func([QuestionId, QuestionDTO], [], []),
  'validateStudentLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Record({
          'test_key' : IDL.Text,
          'registration_id' : RegistrationId,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionType = IDL.Variant({ 'text' : IDL.Null, 'image' : IDL.Null });
  const QuestionDTO = IDL.Record({
    'option_a_en' : IDL.Text,
    'option_a_ta' : IDL.Text,
    'option_b_en' : IDL.Text,
    'option_b_ta' : IDL.Text,
    'option_c_en' : IDL.Text,
    'option_c_ta' : IDL.Text,
    'option_d_en' : IDL.Text,
    'option_d_ta' : IDL.Text,
    'question_type' : QuestionType,
    'question_order' : IDL.Nat,
    'test_key' : IDL.Text,
    'question_text_en' : IDL.Text,
    'question_text_ta' : IDL.Text,
    'is_active' : IDL.Bool,
    'question_image_en' : IDL.Vec(IDL.Nat8),
    'question_image_ta' : IDL.Vec(IDL.Nat8),
    'correct_answer_en' : IDL.Text,
    'correct_answer_ta' : IDL.Text,
  });
  const QuestionId = IDL.Nat;
  const RegistrationInput = IDL.Record({
    'student_name' : IDL.Text,
    'mother_name' : IDL.Text,
    'test_key' : IDL.Text,
    'aadhaar' : IDL.Text,
    'parent_mobile' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'contact_number' : IDL.Text,
    'whatsapp_number' : IDL.Text,
    'exam_group' : IDL.Text,
    'date_of_birth' : IDL.Text,
    'choice1' : IDL.Text,
    'choice2' : IDL.Text,
    'choice3' : IDL.Text,
    'school_name' : IDL.Text,
    'father_name' : IDL.Text,
  });
  const RegistrationId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuizResponseId = IDL.Nat;
  const QuizResponse = IDL.Record({
    'id' : QuizResponseId,
    'question_text' : IDL.Text,
    'is_correct' : IDL.Bool,
    'correct_answer' : IDL.Text,
    'time_taken' : IDL.Nat,
    'score' : IDL.Nat,
    'question_index' : IDL.Nat,
    'student_answer' : IDL.Text,
    'registration_id' : RegistrationId,
    'total_questions' : IDL.Nat,
    'percentage' : IDL.Float64,
    'submitted_at' : IDL.Int,
  });
  const StudentCredentials = IDL.Record({
    'password' : IDL.Text,
    'user_id' : IDL.Text,
    'contact_number' : IDL.Text,
    'is_active' : IDL.Bool,
    'registration_id' : RegistrationId,
  });
  const Registration = IDL.Record({
    'id' : RegistrationId,
    'student_name' : IDL.Text,
    'mother_name' : IDL.Text,
    'registration_date' : IDL.Int,
    'test_key' : IDL.Text,
    'aadhaar' : IDL.Text,
    'parent_mobile' : IDL.Text,
    'email' : IDL.Text,
    'district' : IDL.Text,
    'contact_number' : IDL.Text,
    'whatsapp_number' : IDL.Text,
    'exam_group' : IDL.Text,
    'date_of_birth' : IDL.Text,
    'choice1' : IDL.Text,
    'choice2' : IDL.Text,
    'choice3' : IDL.Text,
    'school_name' : IDL.Text,
    'father_name' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addQuestion' : IDL.Func([QuestionDTO], [QuestionId], []),
    'addRegistration' : IDL.Func([RegistrationInput], [RegistrationId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteQuestion' : IDL.Func([QuestionId], [], []),
    'deleteRegistration' : IDL.Func([RegistrationId], [], []),
    'filterQuizResponses' : IDL.Func(
        [RegistrationId],
        [IDL.Vec(QuizResponse)],
        ['query'],
      ),
    'generateStudentCredentials' : IDL.Func(
        [RegistrationId, IDL.Text],
        [IDL.Record({ 'password' : IDL.Text, 'user_id' : IDL.Text })],
        [],
      ),
    'getAllStudentCredentials' : IDL.Func(
        [],
        [IDL.Vec(StudentCredentials)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCredentialsByRegistrationId' : IDL.Func(
        [RegistrationId],
        [IDL.Opt(StudentCredentials)],
        ['query'],
      ),
    'getFast2SmsApiKey' : IDL.Func([], [IDL.Text], ['query']),
    'getQuestion' : IDL.Func([QuestionId], [IDL.Opt(QuestionDTO)], ['query']),
    'getQuizResponse' : IDL.Func(
        [QuizResponseId],
        [IDL.Opt(QuizResponse)],
        ['query'],
      ),
    'getRegistration' : IDL.Func(
        [RegistrationId],
        [IDL.Opt(Registration)],
        ['query'],
      ),
    'getSmsStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'total_failed' : IDL.Nat,
            'api_key_set' : IDL.Bool,
            'total_sent' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTopQuizScores' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuizResponse)],
        ['query'],
      ),
    'httpTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listQuestions' : IDL.Func(
        [IDL.Text, IDL.Bool],
        [IDL.Vec(QuestionDTO)],
        ['query'],
      ),
    'listQuizResponses' : IDL.Func([], [IDL.Vec(QuizResponse)], ['query']),
    'listRegistrations' : IDL.Func([], [IDL.Vec(Registration)], ['query']),
    'sendSmsCredentials' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'sendTestSms' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool, IDL.Text], []),
    'setFast2SmsApiKey' : IDL.Func([IDL.Text], [], []),
    'submitQuizResponse' : IDL.Func(
        [
          RegistrationId,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
        ],
        [QuizResponseId],
        [],
      ),
    'toggleQuestionActive' : IDL.Func([QuestionId], [], []),
    'updateQuestion' : IDL.Func([QuestionId, QuestionDTO], [], []),
    'validateStudentLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Record({
            'test_key' : IDL.Text,
            'registration_id' : RegistrationId,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };