/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface QuestionDTO {
  'option_a_en' : string,
  'option_a_ta' : string,
  'option_b_en' : string,
  'option_b_ta' : string,
  'option_c_en' : string,
  'option_c_ta' : string,
  'option_d_en' : string,
  'option_d_ta' : string,
  'question_type' : QuestionTypeDTO,
  'question_order' : bigint,
  'test_key' : string,
  'question_text_en' : string,
  'question_text_ta' : string,
  'is_active' : boolean,
  'question_image_en' : Uint8Array,
  'question_image_ta' : Uint8Array,
  'correct_answer_en' : string,
  'correct_answer_ta' : string,
}
export type QuestionId = bigint;
export type QuestionTypeDTO = { 'text' : null } |
  { 'image' : null };
export interface QuizResponse {
  'id' : QuizResponseId,
  'question_text' : string,
  'is_correct' : boolean,
  'correct_answer' : string,
  'time_taken' : bigint,
  'score' : bigint,
  'question_index' : bigint,
  'student_answer' : string,
  'registration_id' : RegistrationId,
  'total_questions' : bigint,
  'percentage' : number,
  'submitted_at' : bigint,
}
export type QuizResponseId = bigint;
export interface Registration {
  'id' : RegistrationId,
  'student_name' : string,
  'registration_date' : bigint,
  'test_key' : string,
  'contact_number' : string,
  'whatsapp_number' : string,
  'exam_group' : string,
  'school_name' : string,
}
export type RegistrationId = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createQuestion' : ActorMethod<[QuestionDTO], QuestionId>,
  'createRegistration' : ActorMethod<
    [string, string, string, string, string, string],
    RegistrationId
  >,
  'deleteRegistration' : ActorMethod<[RegistrationId], undefined>,
  'getAllQuizResponses' : ActorMethod<[], Array<QuizResponse>>,
  'getAllRegistrations' : ActorMethod<[], Array<Registration>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestionsByTestKey' : ActorMethod<[string, boolean], Array<QuestionDTO>>,
  'getResponsesByRegistrationId' : ActorMethod<
    [RegistrationId],
    Array<QuizResponse>
  >,
  'getTopQuizScores' : ActorMethod<[bigint], Array<QuizResponse>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitQuizResponse' : ActorMethod<
    [
      RegistrationId,
      bigint,
      string,
      string,
      string,
      boolean,
      bigint,
      bigint,
      number,
      bigint,
    ],
    QuizResponseId
  >,
  'toggleQuestionActive' : ActorMethod<[QuestionId], undefined>,
  'updateQuestion' : ActorMethod<[QuestionId, QuestionDTO], undefined>,
  'deleteQuestionByTestKeyAndOrder' : ActorMethod<[string, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];