/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface QuizResponse {
    id: QuizResponseId;
    question_text: string;
    is_correct: boolean;
    correct_answer: string;
    time_taken: bigint;
    score: bigint;
    question_index: bigint;
    student_answer: string;
    registration_id: RegistrationId;
    total_questions: bigint;
    percentage: number;
    submitted_at: bigint;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type QuizResponseId = bigint;
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Registration {
    id: RegistrationId;
    student_name: string;
    registration_date: bigint;
    test_key: string;
    contact_number: string;
    whatsapp_number: string;
    exam_group: string;
    school_name: string;
}
export type QuestionId = bigint;
export type RegistrationId = bigint;
export interface QuestionDTO {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: QuestionType;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface StudentCredentials {
    password: string;
    user_id: string;
    contact_number: string;
    is_active: boolean;
    registration_id: RegistrationId;
}
export enum QuestionType {
    text = "text",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addQuestion(dto: QuestionDTO): Promise<QuestionId>;
    addRegistration(student_name: string, school_name: string, contact_number: string, whatsapp_number: string, exam_group: string, test_key: string): Promise<RegistrationId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteQuestion(question_id: QuestionId): Promise<void>;
    deleteRegistration(id: RegistrationId): Promise<void>;
    filterQuizResponses(registration_id: RegistrationId): Promise<Array<QuizResponse>>;
    generateStudentCredentials(registration_id: RegistrationId, contact_number: string): Promise<{
        password: string;
        user_id: string;
    }>;
    getAllStudentCredentials(): Promise<Array<StudentCredentials>>;
    getCallerUserRole(): Promise<UserRole>;
    getCredentialsByRegistrationId(registration_id: RegistrationId): Promise<StudentCredentials | null>;
    getFast2SmsApiKey(): Promise<string>;
    getQuestion(question_id: QuestionId): Promise<QuestionDTO | null>;
    getQuizResponse(id: QuizResponseId): Promise<QuizResponse | null>;
    getRegistration(id: RegistrationId): Promise<Registration | null>;
    getSmsStats(): Promise<{
        total_failed: bigint;
        api_key_set: boolean;
        total_sent: bigint;
    }>;
    getTopQuizScores(limit: bigint): Promise<Array<QuizResponse>>;
    httpTransform(input: TransformationInput): Promise<TransformationOutput>;
    isCallerAdmin(): Promise<boolean>;
    listQuestions(test_key: string, activeOnly: boolean): Promise<Array<QuestionDTO>>;
    listQuizResponses(): Promise<Array<QuizResponse>>;
    listRegistrations(): Promise<Array<Registration>>;
    sendTestSms(phone: string, message: string): Promise<boolean>;
    setFast2SmsApiKey(key: string): Promise<void>;
    submitQuizResponse(registration_id: RegistrationId, question_index: bigint, question_text: string, student_answer: string, correct_answer: string, is_correct: boolean, score: bigint, total_questions: bigint, percentage: number, time_taken: bigint): Promise<QuizResponseId>;
    toggleQuestionActive(question_id: QuestionId): Promise<void>;
    updateQuestion(question_id: QuestionId, dto: QuestionDTO): Promise<void>;
    validateStudentLogin(user_id: string, password: string): Promise<{
        test_key: string;
        registration_id: RegistrationId;
    }>;
}
import type { QuestionDTO as _QuestionDTO, QuestionType as _QuestionType, QuizResponse as _QuizResponse, Registration as _Registration, StudentCredentials as _StudentCredentials, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addQuestion(arg0: QuestionDTO): Promise<QuestionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(to_candid_QuestionDTO_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(to_candid_QuestionDTO_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addRegistration(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<RegistrationId> {
        if (this.processError) {
            try {
                const result = await this.actor.addRegistration(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRegistration(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteQuestion(arg0: QuestionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async deleteRegistration(arg0: RegistrationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRegistration(arg0);
            return result;
        }
    }
    async filterQuizResponses(arg0: RegistrationId): Promise<Array<QuizResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterQuizResponses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterQuizResponses(arg0);
            return result;
        }
    }
    async generateStudentCredentials(arg0: RegistrationId, arg1: string): Promise<{
        password: string;
        user_id: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.generateStudentCredentials(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateStudentCredentials(arg0, arg1);
            return result;
        }
    }
    async getAllStudentCredentials(): Promise<Array<StudentCredentials>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentCredentials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentCredentials();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCredentialsByRegistrationId(arg0: RegistrationId): Promise<StudentCredentials | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCredentialsByRegistrationId(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCredentialsByRegistrationId(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFast2SmsApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFast2SmsApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFast2SmsApiKey();
            return result;
        }
    }
    async getQuestion(arg0: QuestionId): Promise<QuestionDTO | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestion(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestion(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizResponse(arg0: QuizResponseId): Promise<QuizResponse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizResponse(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizResponse(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRegistration(arg0: RegistrationId): Promise<Registration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRegistration(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRegistration(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSmsStats(): Promise<{
        total_failed: bigint;
        api_key_set: boolean;
        total_sent: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSmsStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSmsStats();
            return result;
        }
    }
    async getTopQuizScores(arg0: bigint): Promise<Array<QuizResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopQuizScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopQuizScores(arg0);
            return result;
        }
    }
    async httpTransform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.httpTransform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.httpTransform(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listQuestions(arg0: string, arg1: boolean): Promise<Array<QuestionDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuestions(arg0, arg1);
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuestions(arg0, arg1);
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async listQuizResponses(): Promise<Array<QuizResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.listQuizResponses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listQuizResponses();
            return result;
        }
    }
    async listRegistrations(): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRegistrations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRegistrations();
            return result;
        }
    }
    async sendTestSms(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTestSms(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTestSms(arg0, arg1);
            return result;
        }
    }
    async setFast2SmsApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFast2SmsApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFast2SmsApiKey(arg0);
            return result;
        }
    }
    async submitQuizResponse(arg0: RegistrationId, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: bigint, arg7: bigint, arg8: number, arg9: bigint): Promise<QuizResponseId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizResponse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizResponse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async toggleQuestionActive(arg0: QuestionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleQuestionActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleQuestionActive(arg0);
            return result;
        }
    }
    async updateQuestion(arg0: QuestionId, arg1: QuestionDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, to_candid_QuestionDTO_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, to_candid_QuestionDTO_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async validateStudentLogin(arg0: string, arg1: string): Promise<{
        test_key: string;
        registration_id: RegistrationId;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.validateStudentLogin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateStudentLogin(arg0, arg1);
            return result;
        }
    }
}
function from_candid_QuestionDTO_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionDTO): QuestionDTO {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionType): QuestionType {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuestionDTO]): QuestionDTO | null {
    return value.length === 0 ? null : from_candid_QuestionDTO_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_QuizResponse]): QuizResponse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Registration]): Registration | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudentCredentials]): StudentCredentials | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: _QuestionType;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
}): {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: QuestionType;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
} {
    return {
        option_a_en: value.option_a_en,
        option_a_ta: value.option_a_ta,
        option_b_en: value.option_b_en,
        option_b_ta: value.option_b_ta,
        option_c_en: value.option_c_en,
        option_c_ta: value.option_c_ta,
        option_d_en: value.option_d_en,
        option_d_ta: value.option_d_ta,
        question_type: from_candid_QuestionType_n13(_uploadFile, _downloadFile, value.question_type),
        question_order: value.question_order,
        test_key: value.test_key,
        question_text_en: value.question_text_en,
        question_text_ta: value.question_text_ta,
        is_active: value.is_active,
        question_image_en: value.question_image_en,
        question_image_ta: value.question_image_ta,
        correct_answer_en: value.correct_answer_en,
        correct_answer_ta: value.correct_answer_ta
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    image: null;
}): QuestionType {
    return "text" in value ? QuestionType.text : "image" in value ? QuestionType.image : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionDTO>): Array<QuestionDTO> {
    return value.map((x)=>from_candid_QuestionDTO_n11(_uploadFile, _downloadFile, x));
}
function to_candid_QuestionDTO_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionDTO): _QuestionDTO {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): _QuestionType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: QuestionType;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
}): {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: _QuestionType;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
} {
    return {
        option_a_en: value.option_a_en,
        option_a_ta: value.option_a_ta,
        option_b_en: value.option_b_en,
        option_b_ta: value.option_b_ta,
        option_c_en: value.option_c_en,
        option_c_ta: value.option_c_ta,
        option_d_en: value.option_d_en,
        option_d_ta: value.option_d_ta,
        question_type: to_candid_QuestionType_n3(_uploadFile, _downloadFile, value.question_type),
        question_order: value.question_order,
        test_key: value.test_key,
        question_text_en: value.question_text_en,
        question_text_ta: value.question_text_ta,
        is_active: value.is_active,
        question_image_en: value.question_image_en,
        question_image_ta: value.question_image_ta,
        correct_answer_en: value.correct_answer_en,
        correct_answer_ta: value.correct_answer_ta
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionType): {
    text: null;
} | {
    image: null;
} {
    return value == QuestionType.text ? {
        text: null
    } : value == QuestionType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
