/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type QuizResponseId = bigint;
export interface Registration {
    id: RegistrationId;
    student_name: string;
    registration_date: bigint;
    test_key: string;
    contact_number: string;
    whatsapp_number: string;
    exam_group: string;
    school_name: string;
}
export type QuestionId = bigint;
export type RegistrationId = bigint;
export interface QuestionDTO {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: QuestionTypeDTO;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
}
export interface UserProfile {
    name: string;
}
export interface QuizResponse {
    id: QuizResponseId;
    question_text: string;
    is_correct: boolean;
    correct_answer: string;
    time_taken: bigint;
    score: bigint;
    question_index: bigint;
    student_answer: string;
    registration_id: RegistrationId;
    total_questions: bigint;
    percentage: number;
    submitted_at: bigint;
}
export enum QuestionTypeDTO {
    text = "text",
    image = "image"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createQuestion(dto: QuestionDTO): Promise<QuestionId>;
    createRegistration(student_name: string, school_name: string, contact_number: string, whatsapp_number: string, exam_group: string, test_key: string): Promise<RegistrationId>;
    deleteRegistration(registration_id: RegistrationId): Promise<void>;
    getAllQuizResponses(): Promise<Array<QuizResponse>>;
    getAllRegistrations(): Promise<Array<Registration>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getQuestionsByTestKey(test_key: string, activeOnly: boolean): Promise<Array<QuestionDTO>>;
    getResponsesByRegistrationId(registration_id: RegistrationId): Promise<Array<QuizResponse>>;
    getTopQuizScores(limit: bigint): Promise<Array<QuizResponse>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitQuizResponse(registration_id: RegistrationId, question_index: bigint, question_text: string, student_answer: string, correct_answer: string, is_correct: boolean, score: bigint, total_questions: bigint, percentage: number, time_taken: bigint): Promise<QuizResponseId>;
    toggleQuestionActive(question_id: QuestionId): Promise<void>;
    updateQuestion(question_id: QuestionId, dto: QuestionDTO): Promise<void>;
    deleteQuestionByTestKeyAndOrder(test_key: string, question_order: bigint): Promise<void>;
}
import type { QuestionDTO as _QuestionDTO, QuestionTypeDTO as _QuestionTypeDTO, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createQuestion(arg0: QuestionDTO): Promise<QuestionId> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuestion(to_candid_QuestionDTO_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuestion(to_candid_QuestionDTO_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRegistration(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<RegistrationId> {
        if (this.processError) {
            try {
                const result = await this.actor.createRegistration(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRegistration(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteRegistration(arg0: RegistrationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRegistration(arg0);
            return result;
        }
    }
    async getAllQuizResponses(): Promise<Array<QuizResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuizResponses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuizResponses();
            return result;
        }
    }
    async getAllRegistrations(): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRegistrations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRegistrations();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsByTestKey(arg0: string, arg1: boolean): Promise<Array<QuestionDTO>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsByTestKey(arg0, arg1);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsByTestKey(arg0, arg1);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResponsesByRegistrationId(arg0: RegistrationId): Promise<Array<QuizResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponsesByRegistrationId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponsesByRegistrationId(arg0);
            return result;
        }
    }
    async getTopQuizScores(arg0: bigint): Promise<Array<QuizResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopQuizScores(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopQuizScores(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitQuizResponse(arg0: RegistrationId, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: bigint, arg7: bigint, arg8: number, arg9: bigint): Promise<QuizResponseId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuizResponse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuizResponse(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async toggleQuestionActive(arg0: QuestionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleQuestionActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleQuestionActive(arg0);
            return result;
        }
    }
    async updateQuestion(arg0: QuestionId, arg1: QuestionDTO): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, to_candid_QuestionDTO_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, to_candid_QuestionDTO_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteQuestionByTestKeyAndOrder(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestionByTestKeyAndOrder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestionByTestKeyAndOrder(arg0, arg1);
            return result;
        }
    }
}
function from_candid_QuestionDTO_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionDTO): QuestionDTO {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_QuestionTypeDTO_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuestionTypeDTO): QuestionTypeDTO {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: _QuestionTypeDTO;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
}): {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: QuestionTypeDTO;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
} {
    return {
        option_a_en: value.option_a_en,
        option_a_ta: value.option_a_ta,
        option_b_en: value.option_b_en,
        option_b_ta: value.option_b_ta,
        option_c_en: value.option_c_en,
        option_c_ta: value.option_c_ta,
        option_d_en: value.option_d_en,
        option_d_ta: value.option_d_ta,
        question_type: from_candid_QuestionTypeDTO_n13(_uploadFile, _downloadFile, value.question_type),
        question_order: value.question_order,
        test_key: value.test_key,
        question_text_en: value.question_text_en,
        question_text_ta: value.question_text_ta,
        is_active: value.is_active,
        question_image_en: value.question_image_en,
        question_image_ta: value.question_image_ta,
        correct_answer_en: value.correct_answer_en,
        correct_answer_ta: value.correct_answer_ta
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    image: null;
}): QuestionTypeDTO {
    return "text" in value ? QuestionTypeDTO.text : "image" in value ? QuestionTypeDTO.image : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuestionDTO>): Array<QuestionDTO> {
    return value.map((x)=>from_candid_QuestionDTO_n11(_uploadFile, _downloadFile, x));
}
function to_candid_QuestionDTO_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionDTO): _QuestionDTO {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_QuestionTypeDTO_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionTypeDTO): _QuestionTypeDTO {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: QuestionTypeDTO;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
}): {
    option_a_en: string;
    option_a_ta: string;
    option_b_en: string;
    option_b_ta: string;
    option_c_en: string;
    option_c_ta: string;
    option_d_en: string;
    option_d_ta: string;
    question_type: _QuestionTypeDTO;
    question_order: bigint;
    test_key: string;
    question_text_en: string;
    question_text_ta: string;
    is_active: boolean;
    question_image_en: Uint8Array;
    question_image_ta: Uint8Array;
    correct_answer_en: string;
    correct_answer_ta: string;
} {
    return {
        option_a_en: value.option_a_en,
        option_a_ta: value.option_a_ta,
        option_b_en: value.option_b_en,
        option_b_ta: value.option_b_ta,
        option_c_en: value.option_c_en,
        option_c_ta: value.option_c_ta,
        option_d_en: value.option_d_en,
        option_d_ta: value.option_d_ta,
        question_type: to_candid_QuestionTypeDTO_n5(_uploadFile, _downloadFile, value.question_type),
        question_order: value.question_order,
        test_key: value.test_key,
        question_text_en: value.question_text_en,
        question_text_ta: value.question_text_ta,
        is_active: value.is_active,
        question_image_en: value.question_image_en,
        question_image_ta: value.question_image_ta,
        correct_answer_en: value.correct_answer_en,
        correct_answer_ta: value.correct_answer_ta
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuestionTypeDTO): {
    text: null;
} | {
    image: null;
} {
    return value == QuestionTypeDTO.text ? {
        text: null
    } : value == QuestionTypeDTO.image ? {
        image: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
